language: perl
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
env:
  - "TEST_POD=1 TEST_ONLINE=1 HARNESS_PERL_SWITCHES=-MDevel::Cover"
addons:
  rethinkdb: "2.3"
install:
  - cpanm -n Test::Pod Test::Pod::Coverage
  - cpanm -n Devel::Cover::Report::Coveralls
  - cpanm -n --installdeps .
before_script:
  - rethinkdb --io-threads 2048 --daemon
  - until nc -z localhost 28015; do echo Waiting for RethinkDB; sleep 1; done
after_success:
  - cover -report coveralls
notifications:
  email: false
sudo: false
