##
## This file was generated by Google::ProtocolBuffers (0.08_01)
## on Thu Feb 28 19:46:32 2013 from file query_language.proto
##

use strict;
use warnings;
use Google::ProtocolBuffers;
{
    unless (Builtin::Comparison->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_enum(
            'Builtin::Comparison',
            [
               ['EQ', 1],
               ['NE', 2],
               ['LT', 3],
               ['LE', 4],
               ['GT', 5],
               ['GE', 6],

            ]
        );
    }

    unless (Builtin::BuiltinType->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_enum(
            'Builtin::BuiltinType',
            [
               ['NOT', 1],
               ['GETATTR', 2],
               ['IMPLICIT_GETATTR', 3],
               ['HASATTR', 4],
               ['IMPLICIT_HASATTR', 5],
               ['PICKATTRS', 6],
               ['IMPLICIT_PICKATTRS', 7],
               ['MAPMERGE', 8],
               ['ARRAYAPPEND', 9],
               ['SLICE', 11],
               ['ADD', 14],
               ['SUBTRACT', 15],
               ['MULTIPLY', 16],
               ['DIVIDE', 17],
               ['MODULO', 18],
               ['COMPARE', 19],
               ['FILTER', 20],
               ['MAP', 21],
               ['CONCATMAP', 22],
               ['ORDERBY', 23],
               ['DISTINCT', 24],
               ['LENGTH', 26],
               ['UNION', 27],
               ['NTH', 28],
               ['STREAMTOARRAY', 29],
               ['ARRAYTOSTREAM', 30],
               ['REDUCE', 31],
               ['GROUPEDMAPREDUCE', 32],
               ['ANY', 35],
               ['ALL', 36],
               ['RANGE', 37],
               ['IMPLICIT_WITHOUT', 38],
               ['WITHOUT', 39],

            ]
        );
    }

    unless (Term::TermType->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_enum(
            'Term::TermType',
            [
               ['JSON_NULL', 0],
               ['VAR', 1],
               ['LET', 2],
               ['CALL', 3],
               ['IF', 4],
               ['ERROR', 5],
               ['NUMBER', 6],
               ['STRING', 7],
               ['JSON', 8],
               ['BOOL', 9],
               ['ARRAY', 10],
               ['OBJECT', 11],
               ['GETBYKEY', 12],
               ['TABLE', 13],
               ['JAVASCRIPT', 14],
               ['IMPLICIT_VAR', 15],

            ]
        );
    }

    unless (WriteQuery::WriteQueryType->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_enum(
            'WriteQuery::WriteQueryType',
            [
               ['UPDATE', 1],
               ['DELETE', 2],
               ['MUTATE', 3],
               ['INSERT', 4],
               ['FOREACH', 6],
               ['POINTUPDATE', 7],
               ['POINTDELETE', 8],
               ['POINTMUTATE', 9],

            ]
        );
    }

    unless (Query::QueryType->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_enum(
            'Query::QueryType',
            [
               ['READ', 1],
               ['WRITE', 2],
               ['CONTINUE', 3],
               ['STOP', 4],
               ['META', 5],

            ]
        );
    }

    unless (MetaQuery::MetaQueryType->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_enum(
            'MetaQuery::MetaQueryType',
            [
               ['CREATE_DB', 1],
               ['DROP_DB', 2],
               ['LIST_DBS', 3],
               ['CREATE_TABLE', 4],
               ['DROP_TABLE', 5],
               ['LIST_TABLES', 6],

            ]
        );
    }

    unless (Response::StatusCode->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_enum(
            'Response::StatusCode',
            [
               ['SUCCESS_EMPTY', 0],
               ['SUCCESS_JSON', 1],
               ['SUCCESS_PARTIAL', 2],
               ['SUCCESS_STREAM', 3],
               ['BROKEN_CLIENT', 101],
               ['BAD_QUERY', 102],
               ['RUNTIME_ERROR', 103],

            ]
        );
    }

    unless (Builtin->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'Builtin',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    'Builtin::BuiltinType',
                    'type', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(),
                    Google::ProtocolBuffers::Constants::TYPE_STRING(),
                    'attr', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REPEATED(),
                    Google::ProtocolBuffers::Constants::TYPE_STRING(),
                    'attrs', 3, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(),
                    'Builtin::Comparison',
                    'comparison', 4, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(),
                    'Builtin::Filter',
                    'filter', 5, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(),
                    'Builtin::Map',
                    'map', 6, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(),
                    'Builtin::ConcatMap',
                    'concat_map', 7, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REPEATED(),
                    'Builtin::OrderBy',
                    'order_by', 8, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(),
                    'Reduction',
                    'reduce', 9, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(),
                    'Builtin::GroupedMapReduce',
                    'grouped_map_reduce', 10, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(),
                    'Builtin::Range',
                    'range', 11, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (WriteQuery::Update->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'WriteQuery::Update',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    'Term',
                    'view', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    'Mapping',
                    'mapping', 2, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (MetaQuery->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'MetaQuery',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    'MetaQuery::MetaQueryType',
                    'type', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(),
                    Google::ProtocolBuffers::Constants::TYPE_STRING(),
                    'db_name', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(),
                    'MetaQuery::CreateTable',
                    'create_table', 3, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(),
                    'TableRef',
                    'drop_table', 4, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (ReadQuery->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'ReadQuery',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    'Term',
                    'term', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(),
                    Google::ProtocolBuffers::Constants::TYPE_INT64(),
                    'max_chunk_size', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(),
                    Google::ProtocolBuffers::Constants::TYPE_INT64(),
                    'max_age', 3, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (WriteQuery::PointUpdate->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'WriteQuery::PointUpdate',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    'TableRef',
                    'table_ref', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    Google::ProtocolBuffers::Constants::TYPE_STRING(),
                    'attrname', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    'Term',
                    'key', 3, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    'Mapping',
                    'mapping', 4, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (Reduction->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'Reduction',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    'Term',
                    'base', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    Google::ProtocolBuffers::Constants::TYPE_STRING(),
                    'var1', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    Google::ProtocolBuffers::Constants::TYPE_STRING(),
                    'var2', 3, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    'Term',
                    'body', 4, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (Builtin::Map->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'Builtin::Map',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    'Mapping',
                    'mapping', 1, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (Builtin::GroupedMapReduce->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'Builtin::GroupedMapReduce',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    'Mapping',
                    'group_mapping', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    'Mapping',
                    'value_mapping', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    'Reduction',
                    'reduction', 3, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (Term::Let->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'Term::Let',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REPEATED(),
                    'VarTermTuple',
                    'binds', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    'Term',
                    'expr', 2, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (WriteQuery::Insert->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'WriteQuery::Insert',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    'TableRef',
                    'table_ref', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REPEATED(),
                    'Term',
                    'terms', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(),
                    Google::ProtocolBuffers::Constants::TYPE_BOOL(),
                    'overwrite', 3, 0
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (WriteQuery::PointMutate->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'WriteQuery::PointMutate',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    'TableRef',
                    'table_ref', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    Google::ProtocolBuffers::Constants::TYPE_STRING(),
                    'attrname', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    'Term',
                    'key', 3, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    'Mapping',
                    'mapping', 4, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (Response->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'Response',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    'Response::StatusCode',
                    'status_code', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    Google::ProtocolBuffers::Constants::TYPE_INT64(),
                    'token', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REPEATED(),
                    Google::ProtocolBuffers::Constants::TYPE_STRING(),
                    'response', 3, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(),
                    Google::ProtocolBuffers::Constants::TYPE_STRING(),
                    'error_message', 4, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(),
                    'Response::Backtrace',
                    'backtrace', 5, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (Term::Table->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'Term::Table',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    'TableRef',
                    'table_ref', 1, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (WriteQuery::ForEach->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'WriteQuery::ForEach',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    'Term',
                    'stream', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    Google::ProtocolBuffers::Constants::TYPE_STRING(),
                    'var', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REPEATED(),
                    'WriteQuery',
                    'queries', 3, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (Builtin::ConcatMap->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'Builtin::ConcatMap',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    'Mapping',
                    'mapping', 1, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (Query->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'Query',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    'Query::QueryType',
                    'type', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    Google::ProtocolBuffers::Constants::TYPE_INT64(),
                    'token', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(),
                    'ReadQuery',
                    'read_query', 3, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(),
                    'WriteQuery',
                    'write_query', 4, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(),
                    'MetaQuery',
                    'meta_query', 5, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (WriteQuery->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'WriteQuery',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    'WriteQuery::WriteQueryType',
                    'type', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(),
                    'WriteQuery::Update',
                    'update', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(),
                    'WriteQuery::Delete',
                    'delete', 3, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(),
                    'WriteQuery::Mutate',
                    'mutate', 4, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(),
                    'WriteQuery::Insert',
                    'insert', 5, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(),
                    'WriteQuery::ForEach',
                    'for_each', 7, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(),
                    'WriteQuery::PointUpdate',
                    'point_update', 8, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(),
                    'WriteQuery::PointDelete',
                    'point_delete', 9, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(),
                    'WriteQuery::PointMutate',
                    'point_mutate', 10, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(),
                    Google::ProtocolBuffers::Constants::TYPE_BOOL(),
                    'atomic', 11, 1
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (VarTermTuple->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'VarTermTuple',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    Google::ProtocolBuffers::Constants::TYPE_STRING(),
                    'var', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    'Term',
                    'term', 2, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (Term::Call->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'Term::Call',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    'Builtin',
                    'builtin', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REPEATED(),
                    'Term',
                    'args', 2, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (Builtin::Filter->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'Builtin::Filter',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    'Predicate',
                    'predicate', 1, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (WriteQuery::Mutate->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'WriteQuery::Mutate',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    'Term',
                    'view', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    'Mapping',
                    'mapping', 2, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (Mapping->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'Mapping',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    Google::ProtocolBuffers::Constants::TYPE_STRING(),
                    'arg', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    'Term',
                    'body', 2, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (Response::Backtrace->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'Response::Backtrace',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REPEATED(),
                    Google::ProtocolBuffers::Constants::TYPE_STRING(),
                    'frame', 1, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (Builtin::Range->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'Builtin::Range',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    Google::ProtocolBuffers::Constants::TYPE_STRING(),
                    'attrname', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(),
                    'Term',
                    'lowerbound', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(),
                    'Term',
                    'upperbound', 3, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (Term::GetByKey->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'Term::GetByKey',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    'TableRef',
                    'table_ref', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    Google::ProtocolBuffers::Constants::TYPE_STRING(),
                    'attrname', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    'Term',
                    'key', 3, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (Term->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'Term',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    'Term::TermType',
                    'type', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(),
                    Google::ProtocolBuffers::Constants::TYPE_STRING(),
                    'var', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(),
                    'Term::Let',
                    'let', 3, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(),
                    'Term::Call',
                    'call', 4, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(),
                    'Term::If',
                    'if_', 5, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(),
                    Google::ProtocolBuffers::Constants::TYPE_STRING(),
                    'error', 6, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(),
                    Google::ProtocolBuffers::Constants::TYPE_DOUBLE(),
                    'number', 7, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(),
                    Google::ProtocolBuffers::Constants::TYPE_STRING(),
                    'valuestring', 8, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(),
                    Google::ProtocolBuffers::Constants::TYPE_STRING(),
                    'jsonstring', 9, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(),
                    Google::ProtocolBuffers::Constants::TYPE_BOOL(),
                    'valuebool', 10, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REPEATED(),
                    'Term',
                    'array', 11, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REPEATED(),
                    'VarTermTuple',
                    'object', 12, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(),
                    'Term::GetByKey',
                    'get_by_key', 14, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(),
                    'Term::Table',
                    'table', 15, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(),
                    Google::ProtocolBuffers::Constants::TYPE_STRING(),
                    'javascript', 16, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (TableRef->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'TableRef',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    Google::ProtocolBuffers::Constants::TYPE_STRING(),
                    'db_name', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    Google::ProtocolBuffers::Constants::TYPE_STRING(),
                    'table_name', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(),
                    Google::ProtocolBuffers::Constants::TYPE_BOOL(),
                    'use_outdated', 3, 0
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (WriteQuery::Delete->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'WriteQuery::Delete',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    'Term',
                    'view', 1, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (Builtin::OrderBy->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'Builtin::OrderBy',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    Google::ProtocolBuffers::Constants::TYPE_STRING(),
                    'attr', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(),
                    Google::ProtocolBuffers::Constants::TYPE_BOOL(),
                    'ascending', 2, 1
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (Predicate->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'Predicate',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    Google::ProtocolBuffers::Constants::TYPE_STRING(),
                    'arg', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    'Term',
                    'body', 2, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (WriteQuery::PointDelete->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'WriteQuery::PointDelete',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    'TableRef',
                    'table_ref', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    Google::ProtocolBuffers::Constants::TYPE_STRING(),
                    'attrname', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    'Term',
                    'key', 3, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (Term::If->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'Term::If',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    'Term',
                    'test', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    'Term',
                    'true_branch', 2, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    'Term',
                    'false_branch', 3, undef
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

    unless (MetaQuery::CreateTable->can('_pb_fields_list')) {
        Google::ProtocolBuffers->create_message(
            'MetaQuery::CreateTable',
            [
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(),
                    Google::ProtocolBuffers::Constants::TYPE_STRING(),
                    'datacenter', 1, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_REQUIRED(),
                    'TableRef',
                    'table_ref', 3, undef
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(),
                    Google::ProtocolBuffers::Constants::TYPE_STRING(),
                    'primary_key', 4, "id"
                ],
                [
                    Google::ProtocolBuffers::Constants::LABEL_OPTIONAL(),
                    Google::ProtocolBuffers::Constants::TYPE_INT64(),
                    'cache_size', 5, 1073741824
                ],

            ],
            { 'create_accessors' => 1,  }
        );
    }

}
1;
